modLoader = 'javafml'
loaderVersion = '${loader_version_range}'
license = '${mod_license}'
showAsResourcePack = false

[[mods]]
modId = '${mod_id}'
version = '${mod_version}'
displayName = '${mod_name}'
description = '''${mod_description}'''
logoFile = 'immersive_gambling_logo.png'
authors = '${mod_authors}'
displayURL = 'https://github.com/zhintze/immersive-gambling'

[[dependencies.${mod_id}]]
modId = 'neoforge'
type = 'required'
versionRange = '${neo_version_range}'
ordering = 'NONE'
side = 'BOTH'

[[dependencies.${mod_id}]]
modId = 'minecraft'
type = 'required'
versionRange = '${minecraft_version_range}'
ordering = 'NONE'
side = 'BOTH'

[[dependencies.${mod_id}]]
modId = 'jei'
type = 'optional'
versionRange = '[19,)'
ordering = 'AFTER'
side = 'CLIENT'

[[dependencies.${mod_id}]]
modId = 'immersiveengineering'
type = 'required'
versionRange = '[12.4,)'
ordering = 'AFTER'
side = 'BOTH'
